theme: jekyll-theme-minimal
title: QuantumDNA
description: A tool to calculate lifetimes, average charge separation and dipole moments of excited states along DNA within the formalism of open quantum systems.
