# This file contains all the default values used for the simulations
project_name: "QuantumDNA"

verbose: False
DNA_BASES: ["A", "T", "G", "C", "c"]

SOURCES: ['Hawke2010', 'Simserides2014', 'Mantela2021', 'Simserides2024']
DESCRIPTIONS: ["1P", "2P"]
PARTICLES: ["electron", "hole", "exciton"]
UNITS: ['meV', 'eV', '100meV', 'rad/ps', 'rad/fs', '1/cm', 'K', 'J', '1/fs', '1/ps']
T_UNITS: ['fs', 'ps']
SPECTRAL_DENSITIES: ['debye', 'ohmic']
TB_MODELS: ['WM', 'LM', 'ELM', 'FWM', 'FLM', 'FELM', 'FC']

ham_kwargs_default:
    source: 'Hawke2010'
    description: '2P'
    particles: ['electron','hole','exciton']
    unit: 'rad/ps' 
    interaction_param: 0. # in rad/ps
    relaxation: True
    nn_cutoff: True

diss_kwargs_default:
    loc_deph_rate: 0. # rad/fs
    glob_deph_rate: 0. # rad/fs
    uniform_relaxation: True
    relax_rate: 0. # rad/fs
    relax_rates: {'A': 0, 'T': 0, 'G': 0, 'C': 0, 'B': 0}
    loc_therm: False
    glob_therm: False
    deph_rate: 7. # in rad/ps
    cutoff_freq: 20. # in rad/ps
    reorg_energy: 1. # in rad/ps
    temperature: 300. # in K
    spectral_density: 'debye'
    exponent: 1.

me_kwargs_default: 
    t_steps: 500.
    t_end: 3. # ps
    t_unit: 'ps'
    init_e_state: '(0, 0)'
    init_h_state: '(0, 0)'
    solver_method: 'adams'
