# This file contains all the default values used for the simulations

Ham_kwargs_default:
    source: 'Hawke2010'
    particle: 'exciton' 
    unit: 'rad/ps' 
    interaction_param: 0
    relaxation: True
    nearest_neighbor_cutoff: True

dissipator_kwargs_default:
    loc_deph_rate: 0 # rad/ps
    glob_deph_rate: 0 # rad/ps
    relax_rate: 0 # rad/ps
    loc_therm: False
    glob_therm: False
    deph_rate: 7 # in rad/ps
    cutoff_freq: 20 # in rad/ps
    reorg_energy: 1 # in rad/ps
    temperature: 300 # in K
    spectral_density: 'debye' # 'debye' or 'ohmic'
    exponent: 1
    verbose: False

me_kwargs_default: 
    t_steps: 500
    t_end: 3 # in ps
    init_tb_state: '(0, 0)'
    init_e_state: '(0, 0)'
    init_h_state: '(0, 0)'
