name: qDNA
channels:
    - anaconda
    - defaults
    - conda-forge
dependencies:
    - python = 3.11.5
    - jupyter
    - matplotlib = 3.8.0
    - numpy = 1.26.3
    - pandas = 2.1.4
    - qutip = 4.7.5
    - scipy = 1.11.4
    - setuptools = 68.0.0
    - pyyaml = 6.0.1
    - pytest = 7.4.0
    - seaborn = 0.12.2