version: 2

formats:
  - pdf

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

sphinx:
  configuration: docs/conf.py
  fail_on_warning: true

python:
   install:
  #  - requirements: requirements/requirements.txt
   - requirements: requirements/doc-requirements.txt
