name: Code quality

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r configs/requirements.txt
        pip install -r configs/dev-requirements.txt

    - name: Run black
      continue-on-error: true
      run: black --check .

    - name: Run lint with pylint
      continue-on-error: true
      run: |
        find qDNA tools -type f -name "*.py" ! -name "__init__.py" | xargs pylint

    - name: Run tests with pytest
      run: python -m pytest

    - name: Run tests with coverage
      run: |
        coverage run -m pytest

    - name: Upload coverage to Coveralls
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      run: coveralls
